#robbie is working
GRASS=0
HIGHGRASS=1
WATER=3

GREEN=(0,255,0)
DARKGREEN=(34,139,34)
BLUE=(0,0,255)

titlemap=[
    [GRASS, GRASS, HIGHGRASS]
    [WATER, GRASS, GRASS]
    [WATER, WATER, GRASS]
    [WATER, HIGHGRASS, GRASS]
]
